[package]
name = "bloons_sapper"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
eframe = "0.24.0"
egui = "0.24.0"
inputbot = { git = "https://github.com/obv-mikhail/InputBot", branch = "develop" }
rust_ocr = "0.1.5"
screenshots = "0.8.5"
winapi = "0.3.9"
